### ISSUE TITLE
Profile page fe-logic

### ISSUE THREAD

**Issue by goncaloacbsilva** [SET-IST/website#46]
### Tasks:
- [x] Profile data fetching
- [x] Settings data fetching/patching
- [x] Scanned companies data fetching/patching
- [x] Activities data fetching/patching

### Frontend Logic - Queries management in a Nutshell:
Take ~50min of your time (or speed the video 2x) and watch this video teaching all the basics of [TanStack Query](https://tanstack.com/query/latest) https://www.youtube.com/watch?v=r8Dg0KVnfMA
**Important notes:** 
- The api folder that appears [at this moment](https://youtu.be/r8Dg0KVnfMA?si=pdkULxrvUWbeDBhy&t=1597) is at `lib/frontend/api`. 
- The queries hooks will be located at `lib/frontend/hooks` (see: https://majidlotfinia.medium.com/react-query-best-practices-separating-concerns-with-custom-hooks-3f1bc9051fa2)
- The api client is named `ApiClient` and exported from `core/services/client`
