### ISSUE TITLE
Profile API

### ISSUE THREAD

**Issue by goncaloacbsilva** [SET-IST/website#47]
### Tasks:
- [x] GET api/student/profile
- [x] GET api/student/companies
- [x] GET api/student/enrolments
- [x] GET api/company/profile
- [x] GET api/company/students
- [x] PATCH api/company/profile
- [x] PATCH api/student/profile
