### ISSUE TITLE
Prepare Production and Staging Environments

### ISSUE THREAD

**Issue by goncaloacbsilva** [SET-IST/website#49]
### Tasks:
- [x] Seperate website from services
- [x] Implement Authentik
- [x] Expose Prisma Studio
- [x] Create production branch
