### ISSUE TITLE
Edge Store and AWS api routes

### ISSUE THREAD

**Issue by goncaloacbsilva** [SET-IST/website#51]
### Tasks:
- [x] Setup [Edge Store endpoint](https://edgestore.dev/docs/quick-start#backend) (**for NextJS pages architecture, NOT app**) `/api/blob/[...edgestore].ts` with [AWS S3 config](https://edgestore.dev/docs/providers/aws)
- [x] Configure file bucket `profileImages` with type `IMAGE`
- [x] Configure file bucket `cvs` with type `FILE` and [basic file validation](https://edgestore.dev/docs/configuration#basic-file-validation) to only allow pdfs with a max size of 10MB
- [ ] Create endpoint `GET /api/company/download-cv/{id}` S3
- [x] Create endpoint `GET /api/images/{id}` S3
